/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MC_H_RPCGEN
#define _MC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dictword {
	char word[512];
	char meaning[512];
};
typedef struct dictword dictword;

#define DICTONARTY 0x20000002
#define MCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Insert 1
extern  int * insert_1(dictword *, CLIENT *);
extern  int * insert_1_svc(dictword *, struct svc_req *);
#define Lookup 2
extern  char ** lookup_1(dictword *, CLIENT *);
extern  char ** lookup_1_svc(dictword *, struct svc_req *);
extern int dictonarty_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Insert 1
extern  int * insert_1();
extern  int * insert_1_svc();
#define Lookup 2
extern  char ** lookup_1();
extern  char ** lookup_1_svc();
extern int dictonarty_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dictword (XDR *, dictword*);

#else /* K&R C */
extern bool_t xdr_dictword ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MC_H_RPCGEN */
