/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mc.h"

int * insert_1_svc(dictword *argp, struct svc_req *rqstp)
{
	static int  result;

	 printf ("inide insert function \n");
	/*
	 * insert server code here
	 */

	return &result;
}

char ** lookup_1_svc(dictword *argp, struct svc_req *rqstp)
{
	static char * result;
	 
	printf ("inide lookup function \n");

	/*
	 * insert server code here
	 */

	return &result;
}
