/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mc.h"

bool_t
xdr_dictword (XDR *xdrs, dictword *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->word, 512,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->meaning, 512,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
