/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mc.h"


void dictonartprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	dictword  insert_1_arg;
	char * *result_2;
	dictword  lookup_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DICTONARTPROG, MCVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = insert_1(&insert_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = lookup_1(&lookup_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dictonartprog_1 (host);
	return 0;
}
